
/* File generated by gen_cfile.py. Should not be modified. */

#include "CX_CTL.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 CX_CTL_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 CX_CTL_bDeviceNodeId = 0xFF;

/**************************************************************************/
/* Array of message processing information */

const UNS8 CX_CTL_iam_a_slave = 0;

TIMER_HANDLE CX_CTL_heartBeatTimers[1];

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 CX_CTL_obj1000 = 0x0;	/* 0 */
                    subindex CX_CTL_Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&CX_CTL_obj1000 }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 CX_CTL_obj1001 = 0x0;	/* 0 */
                    subindex CX_CTL_Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CX_CTL_obj1001 }
                     };

/* index 0x1003 :   Pre-defined Error Field */
                    UNS8 CX_CTL_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 CX_CTL_obj1003[] = 
                    {
                      0x0	/* 0 */
                    };
                    ODCallback_t CX_CTL_Index1003_callbacks[] = 
                     {
                       NULL,
                       NULL,
                     };
                    subindex CX_CTL_Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&CX_CTL_highestSubIndex_obj1003 },
                       { RO, uint32, sizeof (UNS32), (void*)&CX_CTL_obj1003[0] }
                     };

/* index 0x1005 :   SYNC COB ID. */
                    UNS32 CX_CTL_obj1005 = 0x0;	/* 0 */
                    ODCallback_t CX_CTL_Index1005_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex CX_CTL_Index1005[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&CX_CTL_obj1005 }
                     };

/* index 0x1006 :   Communication / Cycle Period. */
                    UNS32 CX_CTL_obj1006 = 0x0;	/* 0 */
                    ODCallback_t CX_CTL_Index1006_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex CX_CTL_Index1006[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&CX_CTL_obj1006 }
                     };

/* index 0x1008 :   Manufacturer Device Name. */
                    UNS8 CX_CTL_obj1008[11] = "CX-CTL V1.1";
                    subindex CX_CTL_Index1008[] = 
                     {
                       { RO, visible_string, 11, (void*)&CX_CTL_obj1008 }
                     };

/* index 0x100C :   Guard Time */ 
                    UNS16 CX_CTL_obj100C = 0x0;   /* 0 */

/* index 0x100D :   Life Time Factor */ 
                    UNS8 CX_CTL_obj100D = 0x0;   /* 0 */

/* index 0x1014 :   Emergency COB ID. */
                    UNS32 CX_CTL_obj1014 = 0x80;	/* 128 */
                    subindex CX_CTL_Index1014[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&CX_CTL_obj1014 }
                     };

/* index 0x1016 :   Consumer Heartbeat Time */
                    UNS8 CX_CTL_highestSubIndex_obj1016 = 0;
                    UNS32 CX_CTL_obj1016[]={0};

/* index 0x1017 :   Producer Heartbeat Time. */
                    UNS16 CX_CTL_obj1017 = 0x0;	/* 0 */
                    ODCallback_t CX_CTL_Index1017_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex CX_CTL_Index1017[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&CX_CTL_obj1017 }
                     };

/* index 0x1018 :   Identity. */
                    UNS8 CX_CTL_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 CX_CTL_obj1018_Vendor_ID = 0x0;	/* 0 */
                    UNS32 CX_CTL_obj1018_Product_Code = 0x0;	/* 0 */
                    UNS32 CX_CTL_obj1018_Revision_Number = 0x0;	/* 0 */
                    UNS32 CX_CTL_obj1018_Serial_Number = 0x0;	/* 0 */
                    subindex CX_CTL_Index1018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CX_CTL_highestSubIndex_obj1018 },
                       { RO, uint32, sizeof (UNS32), (void*)&CX_CTL_obj1018_Vendor_ID },
                       { RO, uint32, sizeof (UNS32), (void*)&CX_CTL_obj1018_Product_Code },
                       { RO, uint32, sizeof (UNS32), (void*)&CX_CTL_obj1018_Revision_Number },
                       { RO, uint32, sizeof (UNS32), (void*)&CX_CTL_obj1018_Serial_Number }
                     };

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const indextable CX_CTL_objdict[] = 
{
  { (subindex*)CX_CTL_Index1000,sizeof(CX_CTL_Index1000)/sizeof(CX_CTL_Index1000[0]), 0x1000},
  { (subindex*)CX_CTL_Index1001,sizeof(CX_CTL_Index1001)/sizeof(CX_CTL_Index1001[0]), 0x1001},
  { (subindex*)CX_CTL_Index1005,sizeof(CX_CTL_Index1005)/sizeof(CX_CTL_Index1005[0]), 0x1005},
  { (subindex*)CX_CTL_Index1006,sizeof(CX_CTL_Index1006)/sizeof(CX_CTL_Index1006[0]), 0x1006},
  { (subindex*)CX_CTL_Index1008,sizeof(CX_CTL_Index1008)/sizeof(CX_CTL_Index1008[0]), 0x1008},
  { (subindex*)CX_CTL_Index1014,sizeof(CX_CTL_Index1014)/sizeof(CX_CTL_Index1014[0]), 0x1014},
  { (subindex*)CX_CTL_Index1017,sizeof(CX_CTL_Index1017)/sizeof(CX_CTL_Index1017[0]), 0x1017},
  { (subindex*)CX_CTL_Index1018,sizeof(CX_CTL_Index1018)/sizeof(CX_CTL_Index1018[0]), 0x1018},
};

const indextable * CX_CTL_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks)
{
	int i;
	*callbacks = NULL;
	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
		case 0x1005: i = 2;*callbacks = CX_CTL_Index1005_callbacks; break;
		case 0x1006: i = 3;*callbacks = CX_CTL_Index1006_callbacks; break;
		case 0x1008: i = 4;break;
		case 0x1014: i = 5;break;
		case 0x1017: i = 6;*callbacks = CX_CTL_Index1017_callbacks; break;
		case 0x1018: i = 7;break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &CX_CTL_objdict[i];
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status CX_CTL_PDO_status[1] = {s_PDO_status_Initializer};

const quick_index CX_CTL_firstIndex = {
  0, /* SDO_SVR */
  0, /* SDO_CLT */
  0, /* PDO_RCV */
  0, /* PDO_RCV_MAP */
  0, /* PDO_TRS */
  0 /* PDO_TRS_MAP */
};

const quick_index CX_CTL_lastIndex = {
  0, /* SDO_SVR */
  0, /* SDO_CLT */
  0, /* PDO_RCV */
  0, /* PDO_RCV_MAP */
  0, /* PDO_TRS */
  0 /* PDO_TRS_MAP */
};

const UNS16 CX_CTL_ObjdictSize = sizeof(CX_CTL_objdict)/sizeof(CX_CTL_objdict[0]); 

CO_Data CX_CTL_Data = CANOPEN_NODE_DATA_INITIALIZER(CX_CTL);

