
/* File generated by gen_cfile.py. Should not be modified. */

#include "Hinson_CNS_RFID.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/
UNS8 RfidReadStatus = 0x0;		/* Mapped at index 0x2000, subindex 0x00 */
UNS8 RfidWriteStatus = 0x0;		/* Mapped at index 0x2001, subindex 0x00 */
UNS8 RfidSignalRSSI = 0x0;		/* Mapped at index 0x2002, subindex 0x00 */
UNS8 RfidReadData[] =		/* Mapped at index 0x2003, subindex 0x01 - 0x08 */
  {
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0	/* 0 */
  };
UNS8 RfidWriteData[] =		/* Mapped at index 0x2004, subindex 0x01 - 0x08 */
  {
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0	/* 0 */
  };
UNS8 RfidWriteCommand = 0x0;		/* Mapped at index 0x2005, subindex 0x00 */
UNS8 RfidreadClearCommand = 0x0;		/* Mapped at index 0x2006, subindex 0x00 */

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 Hinson_CNS_RFID_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 Hinson_CNS_RFID_bDeviceNodeId = 0x00;

/**************************************************************************/
/* Array of message processing information */

const UNS8 Hinson_CNS_RFID_iam_a_slave = 1;

TIMER_HANDLE Hinson_CNS_RFID_heartBeatTimers[1];

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 Hinson_CNS_RFID_obj1000 = 0x0;	/* 0 */
                    subindex Hinson_CNS_RFID_Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1000 }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 Hinson_CNS_RFID_obj1001 = 0x0;	/* 0 */
                    subindex Hinson_CNS_RFID_Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Hinson_CNS_RFID_obj1001 }
                     };

/* index 0x1003 :   Pre-defined Error Field */
                    UNS8 Hinson_CNS_RFID_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 Hinson_CNS_RFID_obj1003[] = 
                    {
                      0x0	/* 0 */
                    };
                    ODCallback_t Hinson_CNS_RFID_Index1003_callbacks[] = 
                     {
                       NULL,
                       NULL,
                     };
                    subindex Hinson_CNS_RFID_Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&Hinson_CNS_RFID_highestSubIndex_obj1003 },
                       { RO, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1003[0] }
                     };

/* index 0x1005 :   SYNC COB ID. */
                    UNS32 Hinson_CNS_RFID_obj1005 = 0xA;	/* 10 */
                    ODCallback_t Hinson_CNS_RFID_Index1005_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex Hinson_CNS_RFID_Index1005[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1005 }
                     };

/* index 0x1006 :   Communication / Cycle Period. */
                    UNS32 Hinson_CNS_RFID_obj1006 = 0x0;	/* 0 */
                    ODCallback_t Hinson_CNS_RFID_Index1006_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex Hinson_CNS_RFID_Index1006[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1006 }
                     };

/* index 0x1008 :   Manufacturer Device Name. */
                    UNS8 Hinson_CNS_RFID_obj1008[11] = (UNS8*)"Hinson RFID";
                    subindex Hinson_CNS_RFID_Index1008[] = 
                     {
                       { RO, visible_string, 11, (void*)&Hinson_CNS_RFID_obj1008 }
                     };

/* index 0x100C :   Guard Time */ 
                    UNS16 Hinson_CNS_RFID_obj100C = 0x0;   /* 0 */

/* index 0x100D :   Life Time Factor */ 
                    UNS8 Hinson_CNS_RFID_obj100D = 0x0;   /* 0 */

/* index 0x1014 :   Emergency COB ID. */
                    UNS32 Hinson_CNS_RFID_obj1014 = 0x80;	/* 128 */
                    subindex Hinson_CNS_RFID_Index1014[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1014 }
                     };

/* index 0x1016 :   Consumer Heartbeat Time */
                    UNS8 Hinson_CNS_RFID_highestSubIndex_obj1016 = 0;
                    UNS32 Hinson_CNS_RFID_obj1016[]={0};

/* index 0x1017 :   Producer Heartbeat Time. */
                    UNS16 Hinson_CNS_RFID_obj1017 = 0x0;	/* 0 */
                    ODCallback_t Hinson_CNS_RFID_Index1017_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex Hinson_CNS_RFID_Index1017[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&Hinson_CNS_RFID_obj1017 }
                     };

/* index 0x1018 :   Identity. */
                    UNS8 Hinson_CNS_RFID_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 Hinson_CNS_RFID_obj1018_Vendor_ID = 0x0;	/* 0 */
                    UNS32 Hinson_CNS_RFID_obj1018_Product_Code = 0x0;	/* 0 */
                    UNS32 Hinson_CNS_RFID_obj1018_Revision_Number = 0x0;	/* 0 */
                    UNS32 Hinson_CNS_RFID_obj1018_Serial_Number = 0x0;	/* 0 */
                    subindex Hinson_CNS_RFID_Index1018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Hinson_CNS_RFID_highestSubIndex_obj1018 },
                       { RO, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1018_Vendor_ID },
                       { RO, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1018_Product_Code },
                       { RO, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1018_Revision_Number },
                       { RO, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1018_Serial_Number }
                     };

/* index 0x1020 :   Verify Configuration. */
                    UNS8 Hinson_CNS_RFID_highestSubIndex_obj1020 = 2; /* number of subindex - 1*/
                    UNS32 Hinson_CNS_RFID_obj1020_Configuration_Date = 0x602;	/* 1538 */
                    UNS32 Hinson_CNS_RFID_obj1020_Configuration_Time = 0x0;	/* 0 */
                    subindex Hinson_CNS_RFID_Index1020[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Hinson_CNS_RFID_highestSubIndex_obj1020 },
                       { RW, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1020_Configuration_Date },
                       { RW, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1020_Configuration_Time }
                     };

/* index 0x1200 :   Server SDO Parameter. */
                    UNS8 Hinson_CNS_RFID_highestSubIndex_obj1200 = 2; /* number of subindex - 1*/
                    UNS32 Hinson_CNS_RFID_obj1200_COB_ID_Client_to_Server_Receive_SDO = 0x600;	/* 1536 */
                    UNS32 Hinson_CNS_RFID_obj1200_COB_ID_Server_to_Client_Transmit_SDO = 0x580;	/* 1408 */
                    subindex Hinson_CNS_RFID_Index1200[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Hinson_CNS_RFID_highestSubIndex_obj1200 },
                       { RO, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1200_COB_ID_Client_to_Server_Receive_SDO },
                       { RO, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1200_COB_ID_Server_to_Client_Transmit_SDO }
                     };

/* index 0x1400 :   Receive PDO 1 Parameter. */
                    UNS8 Hinson_CNS_RFID_highestSubIndex_obj1400 = 6; /* number of subindex - 1*/
                    UNS32 Hinson_CNS_RFID_obj1400_COB_ID_used_by_PDO = 0x200;	/* 512 */
                    UNS8 Hinson_CNS_RFID_obj1400_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Hinson_CNS_RFID_obj1400_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Hinson_CNS_RFID_obj1400_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Hinson_CNS_RFID_obj1400_Event_Timer = 0x0;	/* 0 */
                    UNS8 Hinson_CNS_RFID_obj1400_SYNC_start_value = 0x0;	/* 0 */
                    subindex Hinson_CNS_RFID_Index1400[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Hinson_CNS_RFID_highestSubIndex_obj1400 },
                       { RW, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1400_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Hinson_CNS_RFID_obj1400_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&Hinson_CNS_RFID_obj1400_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&Hinson_CNS_RFID_obj1400_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&Hinson_CNS_RFID_obj1400_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&Hinson_CNS_RFID_obj1400_SYNC_start_value }
                     };

/* index 0x1401 :   Receive PDO 2 Parameter. */
                    UNS8 Hinson_CNS_RFID_highestSubIndex_obj1401 = 6; /* number of subindex - 1*/
                    UNS32 Hinson_CNS_RFID_obj1401_COB_ID_used_by_PDO = 0x300;	/* 768 */
                    UNS8 Hinson_CNS_RFID_obj1401_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Hinson_CNS_RFID_obj1401_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Hinson_CNS_RFID_obj1401_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Hinson_CNS_RFID_obj1401_Event_Timer = 0x0;	/* 0 */
                    UNS8 Hinson_CNS_RFID_obj1401_SYNC_start_value = 0x0;	/* 0 */
                    subindex Hinson_CNS_RFID_Index1401[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Hinson_CNS_RFID_highestSubIndex_obj1401 },
                       { RW, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1401_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Hinson_CNS_RFID_obj1401_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&Hinson_CNS_RFID_obj1401_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&Hinson_CNS_RFID_obj1401_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&Hinson_CNS_RFID_obj1401_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&Hinson_CNS_RFID_obj1401_SYNC_start_value }
                     };

/* index 0x1402 :   Receive PDO 3 Parameter. */
                    UNS8 Hinson_CNS_RFID_highestSubIndex_obj1402 = 6; /* number of subindex - 1*/
                    UNS32 Hinson_CNS_RFID_obj1402_COB_ID_used_by_PDO = 0x400;	/* 1024 */
                    UNS8 Hinson_CNS_RFID_obj1402_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Hinson_CNS_RFID_obj1402_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Hinson_CNS_RFID_obj1402_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Hinson_CNS_RFID_obj1402_Event_Timer = 0x0;	/* 0 */
                    UNS8 Hinson_CNS_RFID_obj1402_SYNC_start_value = 0x0;	/* 0 */
                    subindex Hinson_CNS_RFID_Index1402[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Hinson_CNS_RFID_highestSubIndex_obj1402 },
                       { RW, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1402_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Hinson_CNS_RFID_obj1402_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&Hinson_CNS_RFID_obj1402_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&Hinson_CNS_RFID_obj1402_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&Hinson_CNS_RFID_obj1402_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&Hinson_CNS_RFID_obj1402_SYNC_start_value }
                     };

/* index 0x1403 :   Receive PDO 4 Parameter. */
                    UNS8 Hinson_CNS_RFID_highestSubIndex_obj1403 = 6; /* number of subindex - 1*/
                    UNS32 Hinson_CNS_RFID_obj1403_COB_ID_used_by_PDO = 0x500;	/* 1280 */
                    UNS8 Hinson_CNS_RFID_obj1403_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Hinson_CNS_RFID_obj1403_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Hinson_CNS_RFID_obj1403_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Hinson_CNS_RFID_obj1403_Event_Timer = 0x0;	/* 0 */
                    UNS8 Hinson_CNS_RFID_obj1403_SYNC_start_value = 0x0;	/* 0 */
                    subindex Hinson_CNS_RFID_Index1403[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Hinson_CNS_RFID_highestSubIndex_obj1403 },
                       { RW, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1403_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Hinson_CNS_RFID_obj1403_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&Hinson_CNS_RFID_obj1403_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&Hinson_CNS_RFID_obj1403_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&Hinson_CNS_RFID_obj1403_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&Hinson_CNS_RFID_obj1403_SYNC_start_value }
                     };

/* index 0x1600 :   Receive PDO 1 Mapping. */
                    UNS8 Hinson_CNS_RFID_highestSubIndex_obj1600 = 8; /* number of subindex - 1*/
                    UNS32 Hinson_CNS_RFID_obj1600[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex Hinson_CNS_RFID_Index1600[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Hinson_CNS_RFID_highestSubIndex_obj1600 },
                       { RW, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1600[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1600[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1600[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1600[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1600[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1600[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1600[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1600[7] }
                     };

/* index 0x1601 :   Receive PDO 2 Mapping. */
                    UNS8 Hinson_CNS_RFID_highestSubIndex_obj1601 = 8; /* number of subindex - 1*/
                    UNS32 Hinson_CNS_RFID_obj1601[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex Hinson_CNS_RFID_Index1601[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Hinson_CNS_RFID_highestSubIndex_obj1601 },
                       { RW, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1601[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1601[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1601[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1601[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1601[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1601[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1601[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1601[7] }
                     };

/* index 0x1602 :   Receive PDO 3 Mapping. */
                    UNS8 Hinson_CNS_RFID_highestSubIndex_obj1602 = 8; /* number of subindex - 1*/
                    UNS32 Hinson_CNS_RFID_obj1602[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex Hinson_CNS_RFID_Index1602[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Hinson_CNS_RFID_highestSubIndex_obj1602 },
                       { RW, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1602[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1602[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1602[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1602[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1602[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1602[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1602[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1602[7] }
                     };

/* index 0x1603 :   Receive PDO 4 Mapping. */
                    UNS8 Hinson_CNS_RFID_highestSubIndex_obj1603 = 8; /* number of subindex - 1*/
                    UNS32 Hinson_CNS_RFID_obj1603[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex Hinson_CNS_RFID_Index1603[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Hinson_CNS_RFID_highestSubIndex_obj1603 },
                       { RW, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1603[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1603[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1603[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1603[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1603[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1603[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1603[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1603[7] }
                     };

/* index 0x1800 :   Transmit PDO 1 Parameter. */
                    UNS8 Hinson_CNS_RFID_highestSubIndex_obj1800 = 6; /* number of subindex - 1*/
                    UNS32 Hinson_CNS_RFID_obj1800_COB_ID_used_by_PDO = 0x180;	/* 384 */
                    UNS8 Hinson_CNS_RFID_obj1800_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Hinson_CNS_RFID_obj1800_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Hinson_CNS_RFID_obj1800_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Hinson_CNS_RFID_obj1800_Event_Timer = 0x0;	/* 0 */
                    UNS8 Hinson_CNS_RFID_obj1800_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t Hinson_CNS_RFID_Index1800_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex Hinson_CNS_RFID_Index1800[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Hinson_CNS_RFID_highestSubIndex_obj1800 },
                       { RW, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1800_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Hinson_CNS_RFID_obj1800_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&Hinson_CNS_RFID_obj1800_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&Hinson_CNS_RFID_obj1800_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&Hinson_CNS_RFID_obj1800_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&Hinson_CNS_RFID_obj1800_SYNC_start_value }
                     };

/* index 0x1801 :   Transmit PDO 2 Parameter. */
                    UNS8 Hinson_CNS_RFID_highestSubIndex_obj1801 = 6; /* number of subindex - 1*/
                    UNS32 Hinson_CNS_RFID_obj1801_COB_ID_used_by_PDO = 0x280;	/* 640 */
                    UNS8 Hinson_CNS_RFID_obj1801_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Hinson_CNS_RFID_obj1801_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Hinson_CNS_RFID_obj1801_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Hinson_CNS_RFID_obj1801_Event_Timer = 0x0;	/* 0 */
                    UNS8 Hinson_CNS_RFID_obj1801_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t Hinson_CNS_RFID_Index1801_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex Hinson_CNS_RFID_Index1801[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Hinson_CNS_RFID_highestSubIndex_obj1801 },
                       { RW, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1801_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Hinson_CNS_RFID_obj1801_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&Hinson_CNS_RFID_obj1801_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&Hinson_CNS_RFID_obj1801_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&Hinson_CNS_RFID_obj1801_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&Hinson_CNS_RFID_obj1801_SYNC_start_value }
                     };

/* index 0x1802 :   Transmit PDO 3 Parameter. */
                    UNS8 Hinson_CNS_RFID_highestSubIndex_obj1802 = 6; /* number of subindex - 1*/
                    UNS32 Hinson_CNS_RFID_obj1802_COB_ID_used_by_PDO = 0x380;	/* 896 */
                    UNS8 Hinson_CNS_RFID_obj1802_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Hinson_CNS_RFID_obj1802_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Hinson_CNS_RFID_obj1802_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Hinson_CNS_RFID_obj1802_Event_Timer = 0x0;	/* 0 */
                    UNS8 Hinson_CNS_RFID_obj1802_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t Hinson_CNS_RFID_Index1802_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex Hinson_CNS_RFID_Index1802[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Hinson_CNS_RFID_highestSubIndex_obj1802 },
                       { RW, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1802_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Hinson_CNS_RFID_obj1802_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&Hinson_CNS_RFID_obj1802_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&Hinson_CNS_RFID_obj1802_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&Hinson_CNS_RFID_obj1802_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&Hinson_CNS_RFID_obj1802_SYNC_start_value }
                     };

/* index 0x1803 :   Transmit PDO 4 Parameter. */
                    UNS8 Hinson_CNS_RFID_highestSubIndex_obj1803 = 6; /* number of subindex - 1*/
                    UNS32 Hinson_CNS_RFID_obj1803_COB_ID_used_by_PDO = 0x480;	/* 1152 */
                    UNS8 Hinson_CNS_RFID_obj1803_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Hinson_CNS_RFID_obj1803_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Hinson_CNS_RFID_obj1803_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Hinson_CNS_RFID_obj1803_Event_Timer = 0x0;	/* 0 */
                    UNS8 Hinson_CNS_RFID_obj1803_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t Hinson_CNS_RFID_Index1803_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex Hinson_CNS_RFID_Index1803[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Hinson_CNS_RFID_highestSubIndex_obj1803 },
                       { RW, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1803_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Hinson_CNS_RFID_obj1803_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&Hinson_CNS_RFID_obj1803_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&Hinson_CNS_RFID_obj1803_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&Hinson_CNS_RFID_obj1803_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&Hinson_CNS_RFID_obj1803_SYNC_start_value }
                     };

/* index 0x1A00 :   Transmit PDO 1 Mapping. */
                    UNS8 Hinson_CNS_RFID_highestSubIndex_obj1A00 = 8; /* number of subindex - 1*/
                    UNS32 Hinson_CNS_RFID_obj1A00[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex Hinson_CNS_RFID_Index1A00[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Hinson_CNS_RFID_highestSubIndex_obj1A00 },
                       { RW, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1A00[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1A00[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1A00[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1A00[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1A00[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1A00[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1A00[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1A00[7] }
                     };

/* index 0x1A01 :   Transmit PDO 2 Mapping. */
                    UNS8 Hinson_CNS_RFID_highestSubIndex_obj1A01 = 8; /* number of subindex - 1*/
                    UNS32 Hinson_CNS_RFID_obj1A01[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex Hinson_CNS_RFID_Index1A01[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Hinson_CNS_RFID_highestSubIndex_obj1A01 },
                       { RW, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1A01[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1A01[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1A01[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1A01[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1A01[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1A01[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1A01[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1A01[7] }
                     };

/* index 0x1A02 :   Transmit PDO 3 Mapping. */
                    UNS8 Hinson_CNS_RFID_highestSubIndex_obj1A02 = 8; /* number of subindex - 1*/
                    UNS32 Hinson_CNS_RFID_obj1A02[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex Hinson_CNS_RFID_Index1A02[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Hinson_CNS_RFID_highestSubIndex_obj1A02 },
                       { RW, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1A02[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1A02[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1A02[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1A02[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1A02[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1A02[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1A02[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1A02[7] }
                     };

/* index 0x1A03 :   Transmit PDO 4 Mapping. */
                    UNS8 Hinson_CNS_RFID_highestSubIndex_obj1A03 = 8; /* number of subindex - 1*/
                    UNS32 Hinson_CNS_RFID_obj1A03[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex Hinson_CNS_RFID_Index1A03[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Hinson_CNS_RFID_highestSubIndex_obj1A03 },
                       { RW, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1A03[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1A03[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1A03[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1A03[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1A03[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1A03[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1A03[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&Hinson_CNS_RFID_obj1A03[7] }
                     };

/* index 0x2000 :   Mapped variable RfidReadStatus */
                    subindex Hinson_CNS_RFID_Index2000[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&RfidReadStatus }
                     };

/* index 0x2001 :   Mapped variable RfidWriteStatus */
                    subindex Hinson_CNS_RFID_Index2001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&RfidWriteStatus }
                     };

/* index 0x2002 :   Mapped variable RfidSignalRSSI */
                    subindex Hinson_CNS_RFID_Index2002[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&RfidSignalRSSI }
                     };

/* index 0x2003 :   Mapped variable RfidReadData */
                    UNS8 Hinson_CNS_RFID_highestSubIndex_obj2003 = 8; /* number of subindex - 1*/
                    subindex Hinson_CNS_RFID_Index2003[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Hinson_CNS_RFID_highestSubIndex_obj2003 },
                       { RW, uint8, sizeof (UNS8), (void*)&RfidReadData[0] },
                       { RW, uint8, sizeof (UNS8), (void*)&RfidReadData[1] },
                       { RW, uint8, sizeof (UNS8), (void*)&RfidReadData[2] },
                       { RW, uint8, sizeof (UNS8), (void*)&RfidReadData[3] },
                       { RW, uint8, sizeof (UNS8), (void*)&RfidReadData[4] },
                       { RW, uint8, sizeof (UNS8), (void*)&RfidReadData[5] },
                       { RW, uint8, sizeof (UNS8), (void*)&RfidReadData[6] },
                       { RW, uint8, sizeof (UNS8), (void*)&RfidReadData[7] }
                     };

/* index 0x2004 :   Mapped variable RfidWriteData */
                    UNS8 Hinson_CNS_RFID_highestSubIndex_obj2004 = 8; /* number of subindex - 1*/
                    subindex Hinson_CNS_RFID_Index2004[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Hinson_CNS_RFID_highestSubIndex_obj2004 },
                       { RW, uint8, sizeof (UNS8), (void*)&RfidWriteData[0] },
                       { RW, uint8, sizeof (UNS8), (void*)&RfidWriteData[1] },
                       { RW, uint8, sizeof (UNS8), (void*)&RfidWriteData[2] },
                       { RW, uint8, sizeof (UNS8), (void*)&RfidWriteData[3] },
                       { RW, uint8, sizeof (UNS8), (void*)&RfidWriteData[4] },
                       { RW, uint8, sizeof (UNS8), (void*)&RfidWriteData[5] },
                       { RW, uint8, sizeof (UNS8), (void*)&RfidWriteData[6] },
                       { RW, uint8, sizeof (UNS8), (void*)&RfidWriteData[7] }
                     };

/* index 0x2005 :   Mapped variable RfidWriteCommand */
                    subindex Hinson_CNS_RFID_Index2005[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&RfidWriteCommand }
                     };

/* index 0x2006 :   Mapped variable RfidreadClearCommand */
                    subindex Hinson_CNS_RFID_Index2006[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&RfidreadClearCommand }
                     };

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const indextable Hinson_CNS_RFID_objdict[] = 
{
  { (subindex*)Hinson_CNS_RFID_Index1000,sizeof(Hinson_CNS_RFID_Index1000)/sizeof(Hinson_CNS_RFID_Index1000[0]), 0x1000},
  { (subindex*)Hinson_CNS_RFID_Index1001,sizeof(Hinson_CNS_RFID_Index1001)/sizeof(Hinson_CNS_RFID_Index1001[0]), 0x1001},
  { (subindex*)Hinson_CNS_RFID_Index1005,sizeof(Hinson_CNS_RFID_Index1005)/sizeof(Hinson_CNS_RFID_Index1005[0]), 0x1005},
  { (subindex*)Hinson_CNS_RFID_Index1006,sizeof(Hinson_CNS_RFID_Index1006)/sizeof(Hinson_CNS_RFID_Index1006[0]), 0x1006},
  { (subindex*)Hinson_CNS_RFID_Index1008,sizeof(Hinson_CNS_RFID_Index1008)/sizeof(Hinson_CNS_RFID_Index1008[0]), 0x1008},
  { (subindex*)Hinson_CNS_RFID_Index1014,sizeof(Hinson_CNS_RFID_Index1014)/sizeof(Hinson_CNS_RFID_Index1014[0]), 0x1014},
  { (subindex*)Hinson_CNS_RFID_Index1017,sizeof(Hinson_CNS_RFID_Index1017)/sizeof(Hinson_CNS_RFID_Index1017[0]), 0x1017},
  { (subindex*)Hinson_CNS_RFID_Index1018,sizeof(Hinson_CNS_RFID_Index1018)/sizeof(Hinson_CNS_RFID_Index1018[0]), 0x1018},
  { (subindex*)Hinson_CNS_RFID_Index1020,sizeof(Hinson_CNS_RFID_Index1020)/sizeof(Hinson_CNS_RFID_Index1020[0]), 0x1020},
  { (subindex*)Hinson_CNS_RFID_Index1200,sizeof(Hinson_CNS_RFID_Index1200)/sizeof(Hinson_CNS_RFID_Index1200[0]), 0x1200},
  { (subindex*)Hinson_CNS_RFID_Index1400,sizeof(Hinson_CNS_RFID_Index1400)/sizeof(Hinson_CNS_RFID_Index1400[0]), 0x1400},
  { (subindex*)Hinson_CNS_RFID_Index1401,sizeof(Hinson_CNS_RFID_Index1401)/sizeof(Hinson_CNS_RFID_Index1401[0]), 0x1401},
  { (subindex*)Hinson_CNS_RFID_Index1402,sizeof(Hinson_CNS_RFID_Index1402)/sizeof(Hinson_CNS_RFID_Index1402[0]), 0x1402},
  { (subindex*)Hinson_CNS_RFID_Index1403,sizeof(Hinson_CNS_RFID_Index1403)/sizeof(Hinson_CNS_RFID_Index1403[0]), 0x1403},
  { (subindex*)Hinson_CNS_RFID_Index1600,sizeof(Hinson_CNS_RFID_Index1600)/sizeof(Hinson_CNS_RFID_Index1600[0]), 0x1600},
  { (subindex*)Hinson_CNS_RFID_Index1601,sizeof(Hinson_CNS_RFID_Index1601)/sizeof(Hinson_CNS_RFID_Index1601[0]), 0x1601},
  { (subindex*)Hinson_CNS_RFID_Index1602,sizeof(Hinson_CNS_RFID_Index1602)/sizeof(Hinson_CNS_RFID_Index1602[0]), 0x1602},
  { (subindex*)Hinson_CNS_RFID_Index1603,sizeof(Hinson_CNS_RFID_Index1603)/sizeof(Hinson_CNS_RFID_Index1603[0]), 0x1603},
  { (subindex*)Hinson_CNS_RFID_Index1800,sizeof(Hinson_CNS_RFID_Index1800)/sizeof(Hinson_CNS_RFID_Index1800[0]), 0x1800},
  { (subindex*)Hinson_CNS_RFID_Index1801,sizeof(Hinson_CNS_RFID_Index1801)/sizeof(Hinson_CNS_RFID_Index1801[0]), 0x1801},
  { (subindex*)Hinson_CNS_RFID_Index1802,sizeof(Hinson_CNS_RFID_Index1802)/sizeof(Hinson_CNS_RFID_Index1802[0]), 0x1802},
  { (subindex*)Hinson_CNS_RFID_Index1803,sizeof(Hinson_CNS_RFID_Index1803)/sizeof(Hinson_CNS_RFID_Index1803[0]), 0x1803},
  { (subindex*)Hinson_CNS_RFID_Index1A00,sizeof(Hinson_CNS_RFID_Index1A00)/sizeof(Hinson_CNS_RFID_Index1A00[0]), 0x1A00},
  { (subindex*)Hinson_CNS_RFID_Index1A01,sizeof(Hinson_CNS_RFID_Index1A01)/sizeof(Hinson_CNS_RFID_Index1A01[0]), 0x1A01},
  { (subindex*)Hinson_CNS_RFID_Index1A02,sizeof(Hinson_CNS_RFID_Index1A02)/sizeof(Hinson_CNS_RFID_Index1A02[0]), 0x1A02},
  { (subindex*)Hinson_CNS_RFID_Index1A03,sizeof(Hinson_CNS_RFID_Index1A03)/sizeof(Hinson_CNS_RFID_Index1A03[0]), 0x1A03},
  { (subindex*)Hinson_CNS_RFID_Index2000,sizeof(Hinson_CNS_RFID_Index2000)/sizeof(Hinson_CNS_RFID_Index2000[0]), 0x2000},
  { (subindex*)Hinson_CNS_RFID_Index2001,sizeof(Hinson_CNS_RFID_Index2001)/sizeof(Hinson_CNS_RFID_Index2001[0]), 0x2001},
  { (subindex*)Hinson_CNS_RFID_Index2002,sizeof(Hinson_CNS_RFID_Index2002)/sizeof(Hinson_CNS_RFID_Index2002[0]), 0x2002},
  { (subindex*)Hinson_CNS_RFID_Index2003,sizeof(Hinson_CNS_RFID_Index2003)/sizeof(Hinson_CNS_RFID_Index2003[0]), 0x2003},
  { (subindex*)Hinson_CNS_RFID_Index2004,sizeof(Hinson_CNS_RFID_Index2004)/sizeof(Hinson_CNS_RFID_Index2004[0]), 0x2004},
  { (subindex*)Hinson_CNS_RFID_Index2005,sizeof(Hinson_CNS_RFID_Index2005)/sizeof(Hinson_CNS_RFID_Index2005[0]), 0x2005},
  { (subindex*)Hinson_CNS_RFID_Index2006,sizeof(Hinson_CNS_RFID_Index2006)/sizeof(Hinson_CNS_RFID_Index2006[0]), 0x2006},
};

const indextable * Hinson_CNS_RFID_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks)
{
	int i;
	*callbacks = NULL;
	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
		case 0x1005: i = 2;*callbacks = Hinson_CNS_RFID_Index1005_callbacks; break;
		case 0x1006: i = 3;*callbacks = Hinson_CNS_RFID_Index1006_callbacks; break;
		case 0x1008: i = 4;break;
		case 0x1014: i = 5;break;
		case 0x1017: i = 6;*callbacks = Hinson_CNS_RFID_Index1017_callbacks; break;
		case 0x1018: i = 7;break;
		case 0x1020: i = 8;break;
		case 0x1200: i = 9;break;
		case 0x1400: i = 10;break;
		case 0x1401: i = 11;break;
		case 0x1402: i = 12;break;
		case 0x1403: i = 13;break;
		case 0x1600: i = 14;break;
		case 0x1601: i = 15;break;
		case 0x1602: i = 16;break;
		case 0x1603: i = 17;break;
		case 0x1800: i = 18;*callbacks = Hinson_CNS_RFID_Index1800_callbacks; break;
		case 0x1801: i = 19;*callbacks = Hinson_CNS_RFID_Index1801_callbacks; break;
		case 0x1802: i = 20;*callbacks = Hinson_CNS_RFID_Index1802_callbacks; break;
		case 0x1803: i = 21;*callbacks = Hinson_CNS_RFID_Index1803_callbacks; break;
		case 0x1A00: i = 22;break;
		case 0x1A01: i = 23;break;
		case 0x1A02: i = 24;break;
		case 0x1A03: i = 25;break;
		case 0x2000: i = 26;break;
		case 0x2001: i = 27;break;
		case 0x2002: i = 28;break;
		case 0x2003: i = 29;break;
		case 0x2004: i = 30;break;
		case 0x2005: i = 31;break;
		case 0x2006: i = 32;break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &Hinson_CNS_RFID_objdict[i];
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status Hinson_CNS_RFID_PDO_status[4] = {s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer};

const quick_index Hinson_CNS_RFID_firstIndex = {
  9, /* SDO_SVR */
  0, /* SDO_CLT */
  10, /* PDO_RCV */
  14, /* PDO_RCV_MAP */
  18, /* PDO_TRS */
  22 /* PDO_TRS_MAP */
};

const quick_index Hinson_CNS_RFID_lastIndex = {
  9, /* SDO_SVR */
  0, /* SDO_CLT */
  13, /* PDO_RCV */
  17, /* PDO_RCV_MAP */
  21, /* PDO_TRS */
  25 /* PDO_TRS_MAP */
};

const UNS16 Hinson_CNS_RFID_ObjdictSize = sizeof(Hinson_CNS_RFID_objdict)/sizeof(Hinson_CNS_RFID_objdict[0]); 

CO_Data Hinson_CNS_RFID_Data = CANOPEN_NODE_DATA_INITIALIZER(Hinson_CNS_RFID);

