
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef CX_CTL_H
#define CX_CTL_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 CX_CTL_valueRangeTest (UNS8 typeValue, void * value);
const indextable * CX_CTL_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data CX_CTL_Data;

#endif // CX_CTL_H
